#
# projecteuler::problem2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#  
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in teh Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fibonacci_to_4000k
  i1, i2 = 1, 1 #i1, leading index; i2, trailing
  yield i1 #perform initial 1 values of fibonacci
  while i1 < 4000000
    i1, i2 = i1 + i2, i1
    yield i1
  end
end

final_sum = 0
fibonacci_to_4000k { |val| final_sum+=val if val.even? }

puts final_sum
